-- Migration: Fix profiles schema to prevent FK violations and null constraint errors
-- Goal: Ensure profiles.id FK points to auth.users(id), make username nullable
-- Date: 2026-02-04
--
-- This migration:
-- 1. Ensures profiles.id FK references auth.users(id) with ON DELETE CASCADE
-- 2. Makes profiles.username nullable (trigger will auto-fill on insert)
-- 3. Removes any incorrect FK references to public.users

-- Step 1: Check if profiles table exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'profiles') THEN
    RAISE EXCEPTION 'profiles table does not exist. Please create it first.';
  END IF;
END $$;

-- Step 2: Drop any existing FK constraint on profiles.id that references wrong table
DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  -- Find FK constraint on profiles.id that references public.users (wrong!)
  SELECT conname INTO constraint_name
  FROM pg_constraint
  WHERE conrelid = 'public.profiles'::regclass
    AND confrelid = 'public.users'::regclass
    AND contype = 'f'
    AND conkey::text LIKE '%id%';
  
  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS %I', constraint_name);
    RAISE NOTICE 'Dropped incorrect FK constraint: % (was pointing to public.users)', constraint_name;
  ELSE
    RAISE NOTICE 'No FK constraint found from profiles.id to public.users';
  END IF;
END $$;

-- Step 3: Drop any existing FK constraint on profiles.id (we'll recreate it correctly)
DO $$
DECLARE
  constraint_name TEXT;
BEGIN
  -- Find any FK constraint on profiles.id
  SELECT conname INTO constraint_name
  FROM pg_constraint
  WHERE conrelid = 'public.profiles'::regclass
    AND confrelid = 'auth.users'::regclass
    AND contype = 'f'
    AND conkey::text LIKE '%id%';
  
  IF constraint_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS %I', constraint_name);
    RAISE NOTICE 'Dropped existing FK constraint: % (will recreate with ON DELETE CASCADE)', constraint_name;
  ELSE
    RAISE NOTICE 'No existing FK constraint found from profiles.id to auth.users';
  END IF;
END $$;

-- Step 4: Make username nullable (trigger will auto-fill on insert)
ALTER TABLE public.profiles
  ALTER COLUMN username DROP NOT NULL;

-- Step 5: Add FK constraint from profiles.id to auth.users(id) with ON DELETE CASCADE
ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_id_fkey 
    FOREIGN KEY (id) 
    REFERENCES auth.users(id) 
    ON DELETE CASCADE;

-- Step 6: Verify the constraint was created correctly
DO $$
DECLARE
  constraint_exists BOOLEAN;
  constraint_name TEXT;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.profiles'::regclass
      AND confrelid = 'auth.users'::regclass
      AND contype = 'f'
      AND conkey::text LIKE '%id%'
  ) INTO constraint_exists;
  
  IF constraint_exists THEN
    -- Get the constraint name
    SELECT conname INTO constraint_name
    FROM pg_constraint
    WHERE conrelid = 'public.profiles'::regclass
      AND confrelid = 'auth.users'::regclass
      AND contype = 'f'
      AND conkey::text LIKE '%id%'
    LIMIT 1;
    
    RAISE NOTICE '✅ Successfully created FK constraint: profiles.id -> auth.users(id) with ON DELETE CASCADE';
    RAISE NOTICE 'Constraint name: %', constraint_name;
  ELSE
    RAISE WARNING '⚠️ FK constraint may not have been created correctly';
  END IF;
END $$;

-- Step 7: Verify username is nullable
DO $$
DECLARE
  is_nullable TEXT;
BEGIN
  SELECT is_nullable INTO is_nullable
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'profiles'
    AND column_name = 'username';
  
  IF is_nullable = 'YES' THEN
    RAISE NOTICE '✅ Username column is nullable';
  ELSE
    RAISE WARNING '⚠️ Username column is still NOT NULL';
  END IF;
END $$;

-- Step 8: Add comment documenting the change
COMMENT ON CONSTRAINT profiles_id_fkey ON public.profiles IS 
  'Foreign key to auth.users table. profiles.id references auth.users(id) with ON DELETE CASCADE. Username is nullable and auto-generated by trigger if not provided.';

