import type { VercelRequest, VercelResponse } from '@vercel/node';
import { createClient } from '@supabase/supabase-js';
import { URL } from 'url';
import { Resend } from 'resend';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Add CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  res.setHeader('Access-Control-Max-Age', '86400');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { email } = req.body;

    if (!email || typeof email !== 'string') {
      return res.status(400).json({ error: 'Email is required' });
    }

    // Get Supabase credentials from environment
    const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL;
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

    if (!supabaseUrl || !supabaseServiceKey) {
      console.error('[API] Missing Supabase credentials');
      return res.status(500).json({ error: 'Server configuration error' });
    }

    // Create Supabase admin client
    const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey, {
      auth: {
        autoRefreshToken: false,
        persistSession: false
      }
    });

    // Request a password reset from Supabase to get the token
    const { data, error: supabaseError } = await supabaseAdmin.auth.admin.generateLink({
      type: 'recovery',
      email: email,
      redirectTo: `${process.env.EXPO_PUBLIC_API_BASE_URL || 'https://bookshelfapp-five.vercel.app'}/password-reset`,
    });

    if (supabaseError) {
      console.error('[API] Supabase generateLink error:', supabaseError);
      return res.status(200).json({ 
        success: true,
        message: 'If an account exists with this email, a password reset link has been sent.'
      });
    }

    if (!data?.properties?.action_link) {
      console.error('[API] No action_link generated by Supabase');
      return res.status(200).json({ 
        success: true,
        message: 'If an account exists with this email, a password reset link has been sent.'
      });
    }

    // Extract the token from the recovery link
    const recoveryLink = data.properties.action_link;
    const url = new URL(recoveryLink);
    const token = url.searchParams.get('token');
    const type = url.searchParams.get('type');

    if (!token || type !== 'recovery') {
      console.error('[API] Invalid recovery link format');
      return res.status(200).json({ 
        success: true,
        message: 'If an account exists with this email, a password reset link has been sent.'
      });
    }

    // Create deep link that will open the app
    const deepLink = `bookshelfscanner://reset-password?token=${encodeURIComponent(token)}&type=${type}`;
    const webFallbackUrl = `${process.env.EXPO_PUBLIC_API_BASE_URL || 'https://bookshelfapp-five.vercel.app'}/password-reset?token=${encodeURIComponent(token)}&type=${type}`;

    // Attempt to send custom email using Resend SDK
    const emailApiKey = process.env.EMAIL_API_KEY;
    // Default to Resend's test email if no sender is configured
    // To use a custom domain, verify it in Resend first, then set EMAIL_FROM
    const emailFrom = process.env.EMAIL_FROM || 'onboarding@resend.dev';

    if (emailApiKey) {
      try {
        // Use Resend SDK for better reliability
        const resend = new Resend(emailApiKey);
        
        const emailHtml = `
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Reset Your Password</title>
            </head>
            <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
              <div style="background-color: #f8f9fa; border-radius: 10px; padding: 30px; text-align: center;">
                <h1 style="color: #2c3e50; margin-bottom: 20px;">Reset Your Password</h1>
                <p style="color: #666; margin-bottom: 30px;">
                  You requested to reset your password for Bookshelf Scanner. Click the button below to reset your password.
                </p>
                <a href="${deepLink}" style="display: inline-block; background-color: #007AFF; color: #ffffff; text-decoration: none; padding: 15px 30px; border-radius: 8px; font-weight: 600; margin-bottom: 20px;">
                  Reset Password
                </a>
                <p style="color: #999; font-size: 12px; margin-top: 30px;">
                  If the button doesn't work, copy and paste this link into your browser:
                  <br>
                  <a href="${webFallbackUrl}" style="color: #007AFF; text-decoration: underline;">${webFallbackUrl}</a>
                </p>
                <p style="color: #999; font-size: 12px; margin-top: 20px;">
                  If you did not request a password reset, please ignore this email.
                </p>
              </div>
            </body>
          </html>
        `;
        
        const result = await resend.emails.send({
          from: emailFrom,
          to: email,
          subject: 'Reset Your Bookshelf Scanner Password',
          html: emailHtml,
        });

        if (result.error) {
          throw new Error(result.error.message || 'Failed to send email');
        }
        console.log('[API] Password reset email sent successfully via Resend:', result.data?.id);
      } catch (customEmailError) {
        console.error('[API] Error sending custom email:', customEmailError);
        // Fallback to Supabase's default email
        await supabaseAdmin.auth.resetPasswordForEmail(email, {
          redirectTo: deepLink,
        });
      }
    } else {
      // If custom email service not configured, use Supabase's default email
      await supabaseAdmin.auth.resetPasswordForEmail(email, {
        redirectTo: deepLink,
      });
    }

    return res.status(200).json({ 
      success: true,
      message: 'If an account exists with this email, a password reset link has been sent.'
    });
  } catch (error: any) {
    console.error('[API] Error in send-password-reset:', error);
    return res.status(500).json({
      error: error?.message || 'Internal server error',
    });
  }
}

